version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:4.0.4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit-data:/var/lib/rabbitmq

    networks:
      - spring

  postgres1:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

    volumes:
      - data-postgres:/var/lib/postgresql/data

    networks:
      - spring

  ms-stock:
    image: ms-stock:1.0.0-version
    ports:
      - "8080:8080"
    networks:
      - spring
    depends_on:
      - postgres1
      - rabbitmq

  ms-ventas:
    image: ms-ventas:1.0.0-version
    ports:
      - "8081:8081"
    networks:
      - spring
    depends_on:
      - postgres1
      - rabbitmq


networks:
  spring:

volumes:
  data-postgres:
    driver: local
    name: data-postgres
  rabbit-data:
    name: rabbit-data
    driver: local
    